### ISSUE TITLE
Correction on kurtosis?

### ISSUE THREAD

**Issue by nilskvilvang** [davidfoxcroft/lsj-book#14]
On p.78 we find: "Put simply, kurtosis is a measure of the “pointiness” of a data set, as illustrated in Figure 4.12." Several sources, e.g. Westfall (2014) (titled: "Kurtosis as Peakedness, 1905–2014. R.I.P.") argue that "The incorrect notion that kurtosis somehow measures “peakedness” (flatness, pointiness or modality) of a distribution is remarkably persistent, despite attempts by statisticians to set the record straight. This article puts the notion to rest once and for all. Kurtosis tells you virtually nothing about the shape of the peak - its only unambiguous interpretation is in terms of tail extremity; i.e., either existing outliers (for the sample kurtosis) or propensity to produce outliers (for the kurtosis of a probability distribution)."

I suggest you reconsider the notion of kurtosis as a measure of "pointiness" and consider rephrasing that particular segment.

**Comment by davidfoxcroft** [comment]
Thanks for this. I've revised the text on p.78 to reflect this. Very helpful - appreciated. It will appear in the next edition of the text.
