### ISSUE TITLE
Plot error in figure 12.4. - intermediate correlations not displayed

### ISSUE THREAD

**Issue by pederisager** [davidfoxcroft/lsj-book#24]
Figure 12.4. does not seem to display the plots for the .33 and .66 correlations. 
![fig-fig12-4-1](https://user-images.githubusercontent.com/20044958/210347677-e5b26c88-527d-41c0-b141-a03d2bc2ac7a.png)

**Comment by davidfoxcroft** [comment]
Thanks for letting me know. Should be fixed now.
