### ISSUE TITLE
thanks and a typo

### ISSUE THREAD

**Issue by hendxJennifer** [davidfoxcroft/lsj-book#3]
Thanks so much for providing this book.  It's a great resource!  I think there is a typo on page 348 under "Checking the normality assumption" in the 4th sentence it says "if the Shapiro-Wilk test is not significant (i.e. p<.05)..." and I think it should be "...(i.e. p>.05)...".  
Perhaps I misread?

**Comment by davidfoxcroft** [comment]
Yes. good spot thanks. I've fixed it now.
