### ISSUE TITLE
Confusion over gender terminology in first chapters

### ISSUE THREAD

**Issue by Kulei666** [davidfoxcroft/lsj-book#32]
In both chapters **2.1.1** and **1.2** (and possibly elsewhere) 'gender', 'sex', 'male', 'female', 'man', 'woman' are used in a confusing and possibly incorrect way. When speaking about 'sex' it should be implied that it's biological in nature and the only possible answers are 'male', 'female' and variations of 'intersex', whereas when talking about 'gender' it should be implied that it's cultural and/or psychological and it's only about 'woman', 'man', 'nonbinary' (and others).

So: In **2.1.1** Is there a reason for using the confusing 'chromosomal gender' instead of the simple and most commonly used 'sex'? Why is 'female' used to describe 'gender'?

And: In **1.2** for the study about college admissions 'female' and 'woman' are used interchangeably even though they are completely different concepts that cannot be used interchangeably [unless: (1) it has been measured (asked) that no males identify as women, and (2) all females identify as women.].

Edit1: also in **2.7.4** 'gender' is used to describe biological terms like 'female' and 'male'

**Comment by davidfoxcroft** [comment]
The gender terminology in _lsj_ is drawn directly from the book [learning statistics with r](https://learningstatisticswithr.com/) (_lsr_) by Danielle Navarro. I will rely on this source for the correct terminology for gender descriptions and labels. You could raise this as an issue on the [_lsr_ github](https://github.com/djnavarro/rbook/issues)
