### ISSUE TITLE
Figure 7.2 p.136 Black Jeans mia

### ISSUE THREAD

**Issue by Kulei666** [davidfoxcroft/lsj-book#34]
label missing
![ref image](https://user-images.githubusercontent.com/123197787/213875233-d841920e-8c4e-444d-ae65-8b5486647d80.png)

Edit1: Weird, black jeans are visible in the files, maybe it's just a quirk of my .pdf viewer or the dark mode inversion feature?
Edit2: it's not the .pdf viewer nor the inversion, another (browser) .pdf viewer has the same issue:
![ref image2](https://user-images.githubusercontent.com/123197787/213915724-962b45e1-bdd3-4896-97cd-711808b6ccd2.png)
Edit3: here's how it looks in the files:
![fig-fig7-2-1](https://user-images.githubusercontent.com/123197787/213915831-5393bc9c-ce8c-4c2b-a7f6-2c6ce5d21461.png)

**Comment by davidfoxcroft** [comment]
This version of the pdf will soon be archived. A [different pdf version](https://davidfoxcroft.github.io/lsj-book/learning-statistics-with-jamovi.pdf) is being finalised, using the quarto publishing engine - see [here](https://davidfoxcroft.github.io/lsj-book/). We are in the process of checking this new pdf and, once complete, the older version will be removed.

**Comment by davidfoxcroft** [comment]
No action - will be resolved once we move to latest pdf
