### ISSUE TITLE
An error in the book? (factorial ANOVA with no interaction).

### ISSUE THREAD

**Issue by R180** [davidfoxcroft/lsj-book#41]
Thank you for providing this excellent book. I notice what seems to be an error in the presentation of factorial ANOVA with no interactions allowed. The text says "all we have to do is add therapy as a second fixed factor in the analysis" (see the image, below). Then it presents an ANOVA output table pertaining to a model that does not allow interactions. However, as you're aware (since the book says so later on), jamovi's default behavior is to allow interactions and to include the interaction both in the model and in the output table. Thus, to run a no-interactions-allowed ANOVA, the user would have to play around with the "Model Terms" to exclude the interaction. But this isn't explained in the text. 

![lsjbook](https://user-images.githubusercontent.com/16230091/232315726-3aeb082c-4ddf-4abf-bf9e-7ce8a8a040ab.png)

**Comment by davidfoxcroft** [comment]
Yes you are right. The early versions of jamovi did not have interactions as a default. So this needs to be updated now.

**Comment by davidfoxcroft** [comment]
The text and the image have been updated to describe and show jamovi's default behaviour, ie showing interactions
