### ISSUE TITLE
unnecessary repetitions in the text of the book

### ISSUE THREAD

**Issue by Serg58-star** [davidfoxcroft/lsj-book#42]
This page has multiple repetitions of a couple of paragraphs. This looks unsympathetic. I found this in the epilogue, under "Other Ways to Infer". An example of a repeated paragraph: "In other words, instead of assuming the data is (for example) normally distributed, just assume the population looks the same as your sample, then use computers to model the sample distribution for your test statistic, if so the assumption is correct Despite the somewhat dubious assumption (i.e. the distribution of the population is the same as the sample), bootstrapping is a quick and easy technique that works remarkably well in practice for many data analysis problems. results of your experiment many, many times over, based on the double assumptions that (a) the null hypothesis is true and (b) the unknown population distribution is actually very similar to your raw data.". Several times in a row.

**Comment by davidfoxcroft** [comment]
Thanks for raising this. I’ve checked the latest version of the text (via the website -https://davidfoxcroft.github.io/lsj-book/ - always the latest version) and can’t find these repetitions. Would you mind checking again? I suspect a fix was implemented previously though I can’t recall exactly.
Best.
David
