### ISSUE TITLE
Formatting error p. 434

### ISSUE THREAD

**Issue by benjaminPSY** [davidfoxcroft/lsj-book#47]
There is a slight formatting error on p 434 (that unfortunately changes the meaning of the sentence as a whole), such that the superscript on the "2" is missing:

![bild](https://github.com/davidfoxcroft/lsj-book/assets/150910828/e9c957e3-3b15-4bbe-a072-686802c7b41a)

_Edit to clarify:_
It looks like this in the 2019 edition of the book; therefore, I presume a formatting error:
![bild](https://github.com/davidfoxcroft/lsj-book/assets/150910828/66d3ad3d-d3af-4ac9-ade0-691b3928d9f5)

Thank you!

**Comment by davidfoxcroft** [comment]
Good spot. Fixed, thanks!
