### ISSUE TITLE
Issue Finding Data

### ISSUE THREAD

**Issue by gcrone14** [davidfoxcroft/lsj-book#48]
Hello,

I'm a Masters student learning Jamovi right now. I just wanted to indicate that, in future revisions, it was quite difficult to locate the datasets for the textbook. I feel that making it clearer where the datasets can be downloaded would help other readers of the text in the future. Perhaps just adding a note or link making it clearer would be very helpful.

Thanks for reading!

Best,
- Gabe

**Comment by davidfoxcroft** [comment]
Good suggestion! I've added relevant info at the beginning of the preface to the book. Thanks!
