### ISSUE TITLE
Please make epub and mobi available

### ISSUE THREAD

**Issue by kemelzaidan** [davidfoxcroft/lsj-book#8]
Hello,

first, congratulationsn for the great book and software. I started reading it and I'm enjoying a lot. Unfortunately, reading pdfs on a Kindle e-reader is not a pleasent experience. Can you provide mobi files (and maybe epubs) besides the PDFs.

Thanks a lot,

Kemel Zaidan

**Comment by lacrimabundus** [comment]
Hey @kemelzaidan ,

you can do this on your own with "tex4ebook" ([link](https://www.ctan.org/pkg/tex4ebook?lang=en)) in latex (with _tex4ebook -f epub3 lsj.tex_). I just tried it and it worked. Only the images are not displayed.

Regards, Max

**Comment by davidfoxcroft** [comment]
epub version now available in the main branch. html version also available, and this is now the default format  for future development and versions. epub is preferred to mobi as math formulas can be rendered properly in epub, but not in mobi. The epub version in the repository is best read using the [calibre ereader](https://calibre-ebook.com/).
